apiVersion: batch/v1
kind: Job
metadata:
  name: wallabag-db-init
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: postgres:15
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnpg-superuser-secret
                  key: password
            - name: WALLABAG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallabag-db-secret
                  key: password
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Creating Wallabag user and database if not exists..."

              psql -h pg-qa-rw.cnpg-qa.svc.cluster.local -U postgres -v ON_ERROR_STOP=1 <<EOF
              DO \$\$
              BEGIN
                IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'wallabag') THEN
                  CREATE ROLE wallabag LOGIN PASSWORD '${WALLABAG_PASSWORD}';
                END IF;
              END
              \$\$;

              CREATE DATABASE wallabag OWNER wallabag;
              GRANT ALL PRIVILEGES ON DATABASE wallabag TO wallabag;
              EOF
