apiVersion: batch/v1
kind: Job
metadata:
  name: wallabag-db-install
  namespace: cnpg-qa
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: wallabag-installer
          image: wallabag/wallabag:latest
          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: pdo_pgsql
            - name: SYMFONY__ENV__DATABASE_HOST
              value: pg-qa-rw.cnpg-qa.svc.cluster.local
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "5432"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: wallabag
            - name: SYMFONY__ENV__DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: wallabag-db-secret
                  key: username
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallabag-db-secret
                  key: password
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: https://wallabag.lab.aminrj.com
          command: ["bin/console", "wallabag:install", "--env=prod", "--no-interaction"]
