resources:
  - ../../base
  - secrets.yaml
  # - ingress.yaml
  - namespace.yaml

namespace: wallabag-qa

patches:
  - target:
      kind: Deployment
      name: wallabag
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: jdbc:postgresql://wallabag-db-cnpg-v1-rw.cnpg-qa.svc.cluster.local:5432/wallabag
