# databases/n8n/base/database.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db-cnpg-v5
spec:
  description: Fresh Postgres cluster for the n8n automation platform
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 2

  storage:
    size: 10Gi

  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-creds

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: 600Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m

  backup:
    barmanObjectStore:
      destinationPath: https://homelabstorageaccntprod.blob.core.windows.net/n8n-db-clean
      serverName: n8n-db-cnpg-v5
      azureCredentials:
        storageAccount:
          name: n8n-db-storage
          key: container-name
        storageSasToken:
          name: n8n-db-storage
          key: blob-sas
      data:
        compression: gzip
      wal:
        compression: gzip
    retentionPolicy: 7d

  enableSuperuserAccess: false
  primaryUpdateStrategy: unsupervised
