apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-intel-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: threat-intel-automation
  template:
    metadata:
      labels:
        app.kubernetes.io/name: threat-intel-automation
    spec:
      containers:
        - name: automation
          image: python:3.11.9-slim
          command:
            - python
            - /app/server.py
          ports:
            - name: http
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: automation-script
              mountPath: /app
              readOnly: true
      volumes:
        - name: automation-script
          configMap:
            name: threat-intel-automation
