apiVersion: v1
kind: Service
metadata:
  name: threat-intel-metrics
spec:
  selector:
    app.kubernetes.io/name: threat-intel-automation
  ports:
    - name: http
      port: 9101
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: threat-intel-enrichment
spec:
  selector:
    app.kubernetes.io/name: threat-intel-automation
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: threat-intel-exporter
spec:
  selector:
    app.kubernetes.io/name: threat-intel-automation
  ports:
    - name: http
      port: 8081
      targetPort: http
