apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"postgresql.cnpg.io/v1","kind":"Cluster","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"commafeed-db-prod"},"name":"commafeed-db-cnpg-v1","namespace":"cnpg-prod"},"spec":{"backup":{"barmanObjectStore":{"azureCredentials":{"storageAccount":{"key":"container-name","name":"commafeed-db-storage"},"storageSasToken":{"key":"blob-sas","name":"commafeed-db-storage"}},"data":{"compression":"gzip"},"destinationPath":"https://homelabstorageaccntprod.blob.core.windows.net/commafeed-db","wal":{"compression":"gzip"}},"retentionPolicy":"7d"},"bootstrap":{"initdb":{"database":"commafeed","owner":"commafeed","secret":{"name":"commafeed-db-creds"}}},"description":"Postgres cluster for the commafeed application","externalClusters":[{"barmanObjectStore":{"azureCredentials":{"storageAccount":{"key":"container-name","name":"commafeed-db-storage"},"storageSasToken":{"key":"blob-sas","name":"commafeed-db-storage"}},"destinationPath":"https://homelabstorageaccntprod.blob.core.windows.net/commafeed-db-restored","serverName":"commafeed-db-cnpg-v1"},"name":"clusterBackup"}],"imageName":"ghcr.io/cloudnative-pg/postgresql:16.6","inheritedMetadata":{"labels":{"app":"commafeed-database","policy-type":"database"}},"instances":2,"monitoring":{"enablePodMonitor":true,"podMonitorMetricRelabelings":[{"action":"keep","regex":"cnpg_.*|pg_.*","sourceLabels":["__name__"]}],"podMonitorRelabelings":[{"sourceLabels":["__meta_kubernetes_pod_name"],"targetLabel":"pod_name"},{"sourceLabels":["__meta_kubernetes_namespace"],"targetLabel":"namespace"}]},"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"100m","memory":"600Mi"}},"storage":{"size":"15Gi"}}}
  creationTimestamp: "2025-06-27T08:35:04Z"
  generation: 1
  labels:
    argocd.argoproj.io/instance: commafeed-db-prod
  name: commafeed-db-cnpg-v1
  namespace: cnpg-prod
  resourceVersion: "544348"
  uid: c5e5a3e8-c423-4351-8971-b4fcec159868
spec:
  affinity:
    podAntiAffinityType: preferred
  backup:
    barmanObjectStore:
      azureCredentials:
        storageAccount:
          key: container-name
          name: commafeed-db-storage
        storageSasToken:
          key: blob-sas
          name: commafeed-db-storage
      data:
        compression: gzip
      destinationPath: https://homelabstorageaccntprod.blob.core.windows.net/commafeed-db
      wal:
        compression: gzip
    retentionPolicy: 7d
    target: prefer-standby
  bootstrap:
    recovery:
      source: "clusterBackup"
      recoveryTarget:
        backupID: "20250625T160301"  # Use the latest backup
  # bootstrap:
  #   initdb:
  #     database: commafeed
  #     encoding: UTF8
  #     localeCType: C
  #     localeCollate: C
  #     owner: commafeed
  #     secret:
  #       name: commafeed-db-creds
  description: Postgres cluster for the commafeed application
  enablePDB: true
  enableSuperuserAccess: false
  externalClusters:
  - barmanObjectStore:
      azureCredentials:
        storageAccount:
          key: container-name
          name: commafeed-db-storage
        storageSasToken:
          key: blob-sas
          name: commafeed-db-storage
      destinationPath: https://homelabstorageaccntprod.blob.core.windows.net/commafeed-db-restored
      serverName: commafeed-db-cnpg-v1
    name: clusterBackup
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  inheritedMetadata:
    labels:
      app: commafeed-database
      policy-type: database
  instances: 2
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
    podMonitorMetricRelabelings:
    - action: keep
      regex: cnpg_.*|pg_.*
      sourceLabels:
      - __name__
    podMonitorRelabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: pod_name
    - action: replace
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: namespace
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      full_page_writes: "on"
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 600Mi
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 15Gi
  switchoverDelay: 3600
status:
  availableArchitectures:
  - goArch: amd64
    hash: 024c5162e1dee336b21121d781397b347d04939a857d9d8a47664d1796e8b7c9
  - goArch: arm64
    hash: 63f3a3fbe19b8fe1c26a0e516ecb965c3412e390729a02706825399f585d9298
  certificates:
    clientCASecret: commafeed-db-cnpg-v1-ca
    expirations:
      commafeed-db-cnpg-v1-ca: 2025-09-25 08:30:04 +0000 UTC
      commafeed-db-cnpg-v1-replication: 2025-09-25 08:30:04 +0000 UTC
      commafeed-db-cnpg-v1-server: 2025-09-25 08:30:04 +0000 UTC
    replicationTLSSecret: commafeed-db-cnpg-v1-replication
    serverAltDNSNames:
    - commafeed-db-cnpg-v1-rw
    - commafeed-db-cnpg-v1-rw.cnpg-prod
    - commafeed-db-cnpg-v1-rw.cnpg-prod.svc
    - commafeed-db-cnpg-v1-rw.cnpg-prod.svc.cluster.local
    - commafeed-db-cnpg-v1-r
    - commafeed-db-cnpg-v1-r.cnpg-prod
    - commafeed-db-cnpg-v1-r.cnpg-prod.svc
    - commafeed-db-cnpg-v1-r.cnpg-prod.svc.cluster.local
    - commafeed-db-cnpg-v1-ro
    - commafeed-db-cnpg-v1-ro.cnpg-prod
    - commafeed-db-cnpg-v1-ro.cnpg-prod.svc
    - commafeed-db-cnpg-v1-ro.cnpg-prod.svc.cluster.local
    serverCASecret: commafeed-db-cnpg-v1-ca
    serverTLSSecret: commafeed-db-cnpg-v1-server
  cloudNativePGCommitHash: 1535f3c17
  cloudNativePGOperatorHash: 024c5162e1dee336b21121d781397b347d04939a857d9d8a47664d1796e8b7c9
  conditions:
  - lastTransitionTime: "2025-06-27T08:36:47Z"
    message: Cluster is Ready
    reason: ClusterIsReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-06-27T08:35:43Z"
    message: 'unexpected failure invoking barman-cloud-wal-archive: exit status 1'
    reason: ContinuousArchivingFailing
    status: "False"
    type: ContinuousArchiving
  configMapResourceVersion:
    metrics:
      cnpg-default-monitoring: "106019"
  currentPrimary: commafeed-db-cnpg-v1-1
  currentPrimaryTimestamp: "2025-06-27T08:35:38.514611Z"
  healthyPVC:
  - commafeed-db-cnpg-v1-1
  - commafeed-db-cnpg-v1-2
  image: ghcr.io/cloudnative-pg/postgresql:16.6
  instanceNames:
  - commafeed-db-cnpg-v1-1
  - commafeed-db-cnpg-v1-2
  instances: 2
  instancesReportedState:
    commafeed-db-cnpg-v1-1:
      ip: 10.1.105.131
      isPrimary: true
      timeLineID: 1
    commafeed-db-cnpg-v1-2:
      ip: 10.1.23.13
      isPrimary: false
      timeLineID: 1
  instancesStatus:
    healthy:
    - commafeed-db-cnpg-v1-1
    - commafeed-db-cnpg-v1-2
  latestGeneratedNode: 2
  managedRolesStatus: {}
  pgDataImageInfo:
    image: ghcr.io/cloudnative-pg/postgresql:16.6
    majorVersion: 16
  phase: Cluster in healthy state
  poolerIntegrations:
    pgBouncerIntegration: {}
  pvcCount: 2
  readService: commafeed-db-cnpg-v1-r
  readyInstances: 2
  secretsResourceVersion:
    applicationSecretVersion: "451083"
    clientCaSecretVersion: "540576"
    replicationSecretVersion: "540589"
    serverCaSecretVersion: "540576"
    serverSecretVersion: "540583"
  switchReplicaClusterStatus: {}
  targetPrimary: commafeed-db-cnpg-v1-1
  targetPrimaryTimestamp: "2025-06-27T08:35:05.732498Z"
  timelineID: 1
  topology:
    instances:
      commafeed-db-cnpg-v1-1: {}
      commafeed-db-cnpg-v1-2: {}
    nodesUsed: 2
    successfullyExtracted: true
  writeService: commafeed-db-cnpg-v1-rw
