
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin4-data
  namespace: cnpg-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "local-path" # leave blank if you want to use the default storage class
