apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:aminrj/homelab-terraform-gitops-infra.git
    targetRevision: main
    path: argocd/
  destination:
    # server: https://kubernetes.default.svc
    server: "${TARGET_SERVER}"
    namespace: argocd
  syncPolicy: {}
