apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/aminrj/homelab-terraform-gitops-infra.git
      type: git
      name: homelab-gitops
      usernameSecret:
        name: argocd-repo-https
        key: username
      passwordSecret:
        name: argocd-repo-https
        key: password
