apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: git@github.com:aminrj/homelab-terraform-gitops-infra.git
      type: git
      name: homelab-gitops
      sshPrivateKeySecret:
        name: homelab-gitops-repo
        key: sshPrivateKey
