server:
  ingress:
    # enabled: true
    enabled: false
    ingressClassName: nginx
    hosts:
      - minargocd.aminrj.com
    tls:
      - secretName: argocd-tls
        hosts:
          - minargocd.aminrj.com
  service:
    # type: ClusterIP
    type: LoadBalancer

