resources:
  - ../../base
  - secrets.yaml
  - ingress.yaml
  - namespace.yaml
  - alerts.yaml

namespace: wallabag-prod

# patches:
#   - target:
#       kind: Deployment
#       name: wallabag
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/env/0/value
#         value: wallabag-db-cnpg-v1-rw.cnpg-prod.svc.cluster.local
# In your kustomization.yaml
patches:
  - target:
      kind: Deployment
      name: wallabag
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wallabag
      spec:
        template:
          spec:
            containers:
            - name: wallabag
              env:
              - name: SYMFONY__ENV__DATABASE_HOST
                value: wallabag-db-cnpg-v1-rw.cnpg-prod.svc.cluster.local
              - name: POPULATE_DATABASE
                value: "True"
              - name: SYMFONY__ENV__ADMIN_LOGIN
                value: "admin"
              - name: SYMFONY__ENV__ADMIN_PASSWORD
                value: "changeme"
              - name: SYMFONY__ENV__ADMIN_EMAIL
                value: "admin@example.com"
