apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-cnpg-v1
spec:
  backup:
    barmanObjectStore:
      destinationPath: https://homelabstorageaccntprod.blob.core.windows.net/linkding-db-restaured
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: https://homelabstorageaccntprod.blob.core.windows.net/linkding-db-restaured
        serverName: linkding-db
        azureCredentials:
          storageAccount:
            name: linkding-db-storage
            key: container-name
          storageSasToken:
            name: linkding-db-storage
            key: blob-sas
