# databases/linkding/overlays/prod/scheduled-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: linkding-daily-backup
spec:
  schedule: "0 1 * * *"
  backupOwnerReference: cluster
  cluster:
    name: linkding-db-cnpg-v1
  suspend: false
