# infrastructure/storage-monitoring/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../../base

commonLabels:
  environment: prod

patches:
- patch: |-
    - op: add
      path: /metadata/labels/monitoring~1tier
      value: production
  target:
    kind: PrometheusRule
    name: storage-critical-alerts