apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-db-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-qa
    kind: ClusterSecretStore
  target:
    name: n8n-db-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: n8n-db-username
    - secretKey: password
      remoteRef:
        key: n8n-db-password
