# apps/voxora-app/dev/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voxora
  labels:
    app: voxora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voxora
  template:
    metadata:
      labels:
        app: voxora
    spec:
      volumes:
        - name: voxora-data
          persistentVolumeClaim:
            claimName: voxora-data-pvc
      initContainers:
        - name: init-db
          image: secdevopsjourney/voxora-app:latest
          command: ["node", "scripts/init_db"]
          env:
            - name: NODE_ENV
              value: "production"
            - name: SQLITE_DB_PATH
              value: "/data/voxora_dev.db"
          volumeMounts:
            - name: voxora-data
              mountPath: /data
      containers:
        - name: voxora
          image: secdevopsjourney/voxora-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: SQLITE_DB_PATH
              value: "/data/voxora_dev.db"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: voxora-secrets
                  key: NEXTAUTH_SECRET
          volumeMounts:
            - name: voxora-data
              mountPath: /data

