apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voxora-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-staging" # Use if Cert-Manager is installed
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - voxora.dev.aminrj.com
      secretName: voxora-tls # Stores the TLS certificate
  rules:
    - host: voxora.dev.aminrj.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voxora-service
                port:
                  number: 80
