apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-path-storage

resources:
  - ../../base

patchesStrategicMerge:
  - storageclass-patch.yaml

labels:
  - pairs:
      environment: prod