apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: commafeed-db-creds
  namespace: commafeed-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-secret-store
    kind: SecretStore
  target:
    name: commafeed-db-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: commafeed-db-username
    - secretKey: password
      remoteRef:
        key: commafeed-db-password
