apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-dev-cnpg-v1
  namespace: cnpg-dev
spec:
  description: Postgres cluster for the CommaFeed application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 1

  storage:
    size: 5Gi

  monitoring:
    enablePodMonitor: true
    # grafanaDashboard:
    #   create: true
    #   labels:
    #     grafana_dashboard: "1"

  inheritedMetadata:
    labels:
      app: commafeed-database
      policy-type: "database"

  bootstrap:
    recovery:
      source: clusterBackup
      database: commafeed
      owner: commafeed
      secret:
        name: commafeed-db-creds  # created via ExternalSecret in commafeed-dev

  resources:
    requests:
      memory: 600Mi

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: https://homelabstorageaccountdev.blob.core.windows.net/commafeed-db
        serverName: pg-dev
        azureCredentials:
          storageAccount:
            name: commafeed-db-storage
            key: container-name
          storageSasToken:
            name: commafeed-db-storage
            key: blob-sas

  backup:
    barmanObjectStore:
      destinationPath: https://homelabstorageaccountdev.blob.core.windows.net/commafeed-db
      azureCredentials:
        storageAccount:
          name: commafeed-db-storage
          key: container-name
        storageSasToken:
          name: commafeed-db-storage
          key: blob-sas
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d

  # managed:
  #   services:
  #     disabledDefaultServices:
  #       - ro
  #       - r
  #     additional:
  #       - selectorType: rw
  #         serviceTemplate:
  #           metadata:
  #             name: commafeed-db-lb
  #             labels:
  #               cilium-lb-pool: postgres-pool
  #             annotations:
  #               external-dns.alpha.kubernetes.io/hostname: commafeed-db.mischavandenburg.net
  #           spec:
  #             type: LoadBalancer

