apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-db-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-prod
    kind: ClusterSecretStore
  target:
    name: gitea-db-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: gitea-db-username
    - secretKey: password
      remoteRef:
        key: gitea-db-password
    - secretKey: database
      remoteRef:
        key: gitea-db-name

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-db-storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-prod
    kind: ClusterSecretStore
  target:
    name: gitea-db-storage
    creationPolicy: Owner
  data:
    - secretKey: container-name
      remoteRef:
        key: gitea-db-storage-container-name
    - secretKey: blob-sas
      remoteRef:
        key: gitea-db-storage-blob-sas
