prometheus:
  retention: "5d"
  walCompression: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi  # Adjust size as needed

grafana:
  adminPassword: "mysecurepassword" #tmp password
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    size: 10Gi  # Adjust size for Grafana data
    storageClassName: "longhorn"
    accessModes: ["ReadWriteOnce"]

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi  # Alertmanager storage
