apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: rook-ceph
type: "kubernetes.io/rbd"
data:
  # This will need to be updated once MicroCeph is running
  # Get the key with: sudo ceph auth get-key client.admin | base64 -w 0
  key: "REPLACE_WITH_BASE64_ENCODED_CEPH_KEY"