apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wallabag-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    external-dns.alpha.kubernetes.io/target: "90.129.244.3"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wallabag.lab.aminrj.com
      secretName: wallabag-tls
  rules:
    - host: wallabag.lab.aminrj.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wallabag
                port:
                  number: 80
