# databases/commafeed/overlays/prod/destination-path-patch.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-cnpg-v1
spec:
  storage:
    storageClass: local-path
  backup:
    retentionPolicy: "7d"
