# databases/commafeed/overlays/prod/destination-path-patch.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-cnpg-v1
spec:
  backup:
    retentionPolicy: "7d"     # one week retention
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: https://homelabstorageaccntprod.blob.core.windows.net/commafeed-db-clean
        serverName: commafeed-db-cnpg-v1
        azureCredentials:
          storageAccount:
            name: commafeed-db-storage
            key: container-name
          storageSasToken:
            name: commafeed-db-storage
            key: blob-sas
