# databases/commafeed/overlays/prod/scheduled-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: commafeed-daily-backup
spec:
  schedule: "0 3 * * *"  # Daily at 3 AM (off-peak)
  backupOwnerReference: cluster
  cluster:
    name: commafeed-db-cnpg-v1
  suspend: false  # Ensure backups are active
