kind: Deployment
apiVersion: apps/v1
metadata:
  name: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          # image: wallabag/wallabag:latest
          image: ghcr.io/wallabag/docker:2.6.10
          ports:
            - containerPort: 80
          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: "pdo_pgsql"
            - name: SYMFONY__ENV__DATABASE_HOST
              value: "pg-qa-rw.cnpg-qa.svc.cluster.local"
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "5432"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: wallabag-db-secret
                  key: username
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallabag-db-secret
                  key: password
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "https://wallabag.lab.aminrj.com"
            - name: POPULATE_DATABASE
              value: "True"
