# databases/linkding/overlays/prod/cluster-restore.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-restore-v16  # New name to avoid version history
spec:
  instances: 1
  
  imageName: "quay.io/enterprisedb/postgresql:16.1"
  
  storage:
    size: "15Gi"
    storageClass: "microk8s-hostpath"
  
  bootstrap:
    recovery:
      source: clusterBackup
      
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: https://homelabstorageaccntprod.blob.core.windows.net/linkding-db
        serverName: linkding-db-cnpg-v1
        azureCredentials:
          storageAccount:
            name: linkding-db-storage
            key: container-name
          storageSasToken:
            name: linkding-db-storage
            key: blob-sas

  backup:
    barmanObjectStore:
      destinationPath: https://homelabstorageaccntprod.blob.core.windows.net/linkding-db-restored
      azureCredentials:
        storageAccount:
          name: linkding-db-storage
          key: container-name
        storageSasToken:
          name: linkding-db-storage
          key: blob-sas
