apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:aminrj/homelab-terraform-gitops-infra.git
        revision: main
        directories:
          - path: apps/*/* # auto-detect all apps & env
  template:
    metadata:
      name: '{{path[1]}}-{{path[2]}}'
    spec:
      project: default #Add project separation later as needed
      source:
        repoURL: git@github.com:aminrj/homelab-terraform-gitops-infra.git
        targetRevision: main
        path: 'apps/{{path[1]}}/{{path[2]}}' #Example: apps/nextjs-app/dev
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}-{{path[2]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
