apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/aminrj/homelab-terraform-gitops-infra.git
        revision: main
        directories:
          - path: apps/*/overlays/* # <app-name>/overlays/<env> auto-detect all apps & env
  template:
    metadata:
      name: '{{path[1]}}-{{path[3]}}' # example: commafeed-db-dev
    spec:
      project: default #Add project separation later as needed
      source:
        repoURL: https://github.com/aminrj/homelab-terraform-gitops-infra.git
        targetRevision: main
        path: 'apps/{{path[1]}}/overlays/{{path[3]}}' #Example: apps/nextjs-app/dev
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[3]}}' # dev, qa, prod as namespace (simpler - for now)
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
