apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextjs-app
  namespace: argocd
spec:
  project: web-apps
  source:
    repoURL: git@github.com:aminrj/terraform-gitops-infra.git
    targetRevision: main
    path: apps/nextjs-app/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
