apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: databases
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:aminrj/homelab-terraform-gitops-infra.git
        revision: main
        directories:
          - path: databases/wallabag/overlays/prod
            exclude: true
          - path: databases/*/overlays/prod
  template:
    metadata:
      name: 'db-{{path[1]}}-{{path[3]}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:aminrj/homelab-terraform-gitops-infra.git
        targetRevision: main
        path: 'databases/{{path[1]}}/overlays/{{path[3]}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'cnpg-{{path[3]}}'  # cnpg-dev, cnpg-qa, cnpg-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
