# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: external-secrets-infra
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/aminrj/homelab-terraform-gitops-infra.git
#     targetRevision: main
#     path: infrastructure/external-secrets
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: external-secrets  # or leave it blank, ClusterSecretStore is cluster-wide
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-infra-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aminrj/homelab-terraform-gitops-infra.git
    targetRevision: main
    path: infrastructure/external-secrets/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-infra-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aminrj/homelab-terraform-gitops-infra.git
    targetRevision: main
    path: infrastructure/external-secrets/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-infra-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aminrj/homelab-terraform-gitops-infra.git
    targetRevision: main
    path: infrastructure/external-secrets/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
