apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-infra-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:aminrj/homelab-terraform-gitops-infra.git
    targetRevision: main
    path: infrastructure/external-secrets/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ClusterSecretStore
      jsonPointers:
        - /metadata/finalizers
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /metadata/finalizers
