resources:
  - ../../base
  - ingress.yaml

namespace: cnpg-qa

# patches:
#   - target:
#       kind: Deployment
#       name: listmonk
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/env/0/value
#         value: jdbc:postgresql://pg-qa-rw.cnpg-qa.svc.cluster.local:5432/listmonk
