apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: listmonk-db-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-qa
    kind: ClusterSecretStore
  target:
    name: listmonk-db-creds
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: listmonk-db-username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: listmonk-db-password
