provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey

logLevel: debug

sources:
  - ingress

policy: sync

extraArgs:
  - --annotation-filter=external-dns.alpha.kubernetes.io/enabled=true
