resources:
  - ../../base
  - secrets.yaml

namespace: cnpg-dev

patches:
  - target:
      kind: Deployment
      name: commafeed
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: jdbc:postgresql://pg-dev-rw.cnpg-dev.svc.cluster.local:5432/commafeed
