apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: commafeed-db-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-dev
    kind: ClusterSecretStore
  target:
    name: commafeed-db-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: commafeed-db-username
    - secretKey: password
      remoteRef:
        key: commafeed-db-password
