resources:
  - ../../base
  - secrets.yaml
  - ingress.yaml
  - namespace.yaml

namespace: listmonk-prod

patches:
  - target:
      kind: Deployment
      name: listmonk
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: listmonk
      spec:
        template:
          spec:
            containers:
            - name: listmonk
              env:
              - name: LISTMONK_DB__HOST
                value: listmonk-db-cnpg-v1-rw.cnpg-prod.svc.cluster.local
