apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: listmonk-db-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-prod
    kind: ClusterSecretStore
  target:
    name: listmonk-db-creds
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: listmonk-db-username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: listmonk-db-password
---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: listmonk-admin-creds
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: azure-kv-store-prod
#     kind: ClusterSecretStore
#   target:
#     name: listmonk-admin-creds
#     creationPolicy: Owner
#   data:
#     - secretKey: password
#       remoteRef:
#         key: listmonk-db-password
#     - secretKey: username
#       remoteRef:
#         key: listmonk-db-username
