# apps/ollama/base/pv-ollama-model-cache.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-model-cache
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    volumeHandle: ollama-model-cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - microk8s-prod-llm1
