
apiVersion: v1
kind: Service
metadata:
  name: ollama-service  # Standardized name
  namespace: ollama
spec:
  selector:
    app: ollama  # Make sure this matches your deployment
  ports:
    - name: http
      port: 11434
      targetPort: 11434
  type: ClusterIP
