#databases/wallabag/base/database.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-db-cnpg-v1
spec:
  description: Postgres cluster for the wallabag application
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6  # Fixed: match your backup version
  instances: 1

  storage:
    size: 15Gi
    storageClass: local-path

 # Enhanced monitoring configuration
  monitoring:
    # enabled: true
    enablePodMonitor: true
    podMonitorMetricRelabelings:
      - sourceLabels: [__name__]
        regex: 'cnpg_.*|pg_.*'
        action: keep
    podMonitorRelabelings:
      - sourceLabels: [__meta_kubernetes_pod_name]
        targetLabel: pod_name
      - sourceLabels: [__meta_kubernetes_namespace]
        targetLabel: namespace
        
  # Resource configuration
  resources:
    requests:
      memory: 600Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m

  inheritedMetadata:
    labels:
      app: wallabag-database
      policy-type: "database"

  bootstrap:
    initdb:
      database: wallabag
      owner: wallabag
      secret:
        name: wallabag-db-creds
      postInitApplicationSQL:
        - ALTER DATABASE wallabag OWNER TO wallabag;
        - ALTER SCHEMA public OWNER TO wallabag;
        - GRANT ALL PRIVILEGES ON SCHEMA public TO wallabag;

  backup: {}
