apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-cnpg-v1
spec:
  description: Postgres cluster for the commafeed application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 1

  storage:
    size: 5Gi

  monitoring:
    enablePodMonitor: true

  inheritedMetadata:
    labels:
      app: commafeed-database
      policy-type: "database"

  bootstrap:
    initdb:
      database: commafeed
      owner: commafeed
      secret:
        name: commafeed-db-creds   # Same ExternalSecret you already have

  resources:
    requests:
      memory: 600Mi

  backup:
    barmanObjectStore:
      destinationPath: https://homelabstorageaccountdev.blob.core.windows.net/commafeed-db
      azureCredentials:
        storageAccount:
          name: commafeed-db-storage
          key: container-name
        storageSasToken:
          name: commafeed-db-storage
          key: blob-sas
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d
