apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db-cnpg-v1
spec:
  description: Postgres cluster for the commafeed application
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6  # Fixed: match your backup version
  instances: 2

  storage:
    size: 15Gi
    # storageClass: longhorn  # Added: now that Longhorn is working

  monitoring:
    enablePodMonitor: true

  inheritedMetadata:
    labels:
      app: commafeed-database
      policy-type: "database"

  # Fixed bootstrap for recovery
  bootstrap:
    recovery:
      source: "clusterBackup"
      # recoveryTarget:
      #   targetTime: "2025-06-14 10:59:31"  # Use timestamp instead of backup name

  resources:
    requests:
      memory: 600Mi

  backup:
    barmanObjectStore:
      destinationPath: https://homelabstorageaccountdev.blob.core.windows.net/commafeed-db  # Base uses dev
      azureCredentials:
        storageAccount:
          name: commafeed-db-storage
          key: container-name
        storageSasToken:
          name: commafeed-db-storage
          key: blob-sas
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d

