# infrastructure/storage-cleanup/base/cleanup-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: storage-cleanup
  namespace: kube-system
spec:
  # Run daily at 2:00 AM
  schedule: "0 2 * * *"
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400  # 24 hours
      template:
        metadata:
          labels:
            app: storage-cleanup
            component: cleanup-job
        spec:
          serviceAccountName: storage-cleanup
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - |
              # Install jq for JSON processing
              apt-get update -qq && apt-get install -y -qq jq curl

              # Make script executable and run it
              chmod +x /scripts/cleanup.sh
              /scripts/cleanup.sh
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: false  # Need write access for package installation
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            volumeMounts:
            - name: cleanup-script
              mountPath: /scripts
              readOnly: true
            env:
            - name: KUBECTL_VERSION
              value: "v1.28.0"
          volumes:
          - name: cleanup-script
            configMap:
              name: storage-cleanup-script
              defaultMode: 0755