# infrastructure/storage-cleanup/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - cleanup-rbac.yaml
  - cleanup-script.yaml
  - cleanup-cronjob.yaml

commonLabels:
  app.kubernetes.io/name: storage-cleanup
  app.kubernetes.io/part-of: homelab-infrastructure
  app.kubernetes.io/component: maintenance