apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: listmonk-db-cnpg-v1
spec:
  backup:
    barmanObjectStore:
      destinationPath: https://homelabstorageaccountqa.blob.core.windows.net/listmonk-db
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: https://homelabstorageaccountqa.blob.core.windows.net/listmonk-db
        serverName: listmonk-db
        azureCredentials:
          storageAccount:
            name: listmonk-db-storage
            key: container-name
          storageSasToken:
            name: listmonk-db-storage
            key: blob-sas
