apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aminrj/homelab-terraform-gitops-infra # but the gitops repo
    targetRevision: main
    path: apps/nextjs-app/dev # Path to the app in the GitOps repo
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
