
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store-prod
  labels:
    argocd.argoproj.io/instance: external-secrets-infra-prod
spec:
  provider:
    azurekv:
      tenantId: 8052b405-12c9-4ba1-a5b3-117899e42975
      vaultUrl: https://hlab-keyvault-prod.vault.azure.net
      authType: ServicePrincipal
      environmentType: PublicCloud
      authSecretRef:
        clientId:
          name: azure-creds-prod
          key: client-id
          namespace: external-secrets
        clientSecret:
          name: azure-creds-prod
          key: client-secret
          namespace: external-secrets
