apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-config
  namespace: rook-ceph
data:
  config: |
    [global]
    mon_host = 10.0.30.10:6789,10.0.30.16:6789,10.0.30.17:6789
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: rook-ceph
type: "kubernetes.io/rbd"
data:
  # This will be populated once MicroCeph is running
  # Run: sudo ceph auth get-key client.admin | base64
  key: ""