resources:
  - ../../base/commafeed-db
patches:
  - target:
      kind: Secret
      name: commafeed-db-secret
    patch: |-
      - op: replace
        path: /stringData/password
        value: commafeed-qa-password
