namespace: cnpg-qa

resources:
  - ../../base

patches:
  - target:
      kind: Secret
      name: commafeed-db-secret
    patch: |-
      - op: replace
        path: /stringData/password
        value: commafeed-qa-password

  - target:
      kind: Secret
      name: cnpg-superuser-secret
    patch: |-
      - op: replace
        path: /stringData/password
        value: pg-superuser-qa
