resources:
  - ../../base
  # - commafeed-db-secret.yaml
  - bootstrap-job.yaml

namespace: cnpg-qa

patches:
  - target:
      kind: Deployment
      name: commafeed
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: jdbc:postgresql://pg-qa-rw.cnpg-qa.svc.cluster.local:5432/commafeed
