hostNetwork:
  enabled: true

sourcePort: 4443
args:
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP

# Optional: set resource requests/limits
resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 400m
    memory: 300Mi

# Optional: enable metrics if you want to expose them to Prometheus
metrics:
  enabled: true

apiService:
  create: true

# Optional: enable for Prometheus scraping (only if metrics.enabled: true)
serviceMonitor:
  enabled: true
