# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listmonk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listmonk
  template:
    metadata:
      labels:
        app: listmonk
    spec:
      containers:
        - name: listmonk
          image: listmonk/listmonk:latest
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: LISTMONK_DB__HOST
              value: listmonk-db-cnpg-v1-rw.cnpg-prod.svc.cluster.local  # Replace with QA DB in overlays
            - name: LISTMONK_APP__ADDRESS
              value: "0.0.0.0:9000"
            - name: LISTMONK_DB__PORT
              value: "5432"
            - name: LISTMONK_DB__USER
              valueFrom:
                secretKeyRef:
                  name: listmonk-db-creds
                  key: POSTGRES_USER
                  # key: username
            - name: LISTMONK_DB__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: listmonk-db-creds
                  key: POSTGRES_PASSWORD
                  # key: password
            - name: LISTMONK_DB__DATABASE
              value: "listmonk"
            - name: LISTMONK_DB__SSL_MODE
              value: "disable"
            - name: LISTMONK_ADMIN_USER
              value: "admin"
            - name: LISTMONK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: listmonk-db-creds
                  key: POSTGRES_PASSWORD
                  # key: password
          command: 
            - /bin/sh
            - -c
            - |
              ./listmonk --install --idempotent --yes &&
              ./listmonk --upgrade --yes &&
              ./listmonk
