apiVersion: v1
kind: Secret
metadata:
  name: listmonk-db-secret
type: Opaque
stringData:
  username: listmonk
  password: listmonk

---
apiVersion: v1
kind: Secret
metadata:
  name: listmonk-admin-secret
type: Opaque
stringData:
  password: changeme
