apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store-dev
    kind: ClusterSecretStore
  target:
    name: linkding-db-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: linkding-db-username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: linkding-db-password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: linkding-db-name
