# databases/n8n/overlays/prod/destination-path-patch.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db-cnpg-v3
spec:
  backup:
    barmanObjectStore:
      serverName: n8n-db-cnpg-v3
    retentionPolicy: "7d"
