# databases/n8n/overlays/prod/destination-path-patch.yaml
# Backup configuration commented out during restore
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db-cnpg-v5
spec:
  storage:
    storageClass: local-path
  # backup:
  #   barmanObjectStore:
  #     serverName: n8n-db-cnpg-v5
  #   retentionPolicy: "7d"
