# databases/n8n/overlays/prod/scheduled-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: prod-daily-backup
spec:
  schedule: "0 2 * * *"  # Daily at 3 AM (off-peak)
  backupOwnerReference: cluster
  cluster:
    name: n8n-db-cnpg-v2
  suspend: false  # Ensure backups are active

