# databases/n8n/overlays/prod/scheduled-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: n8n-daily-backup
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM UTC
  backupOwnerReference: cluster
  cluster:
    name: n8n-db-cnpg-v3
  suspend: false  # Ensure backups are active

